name: Core

on:
  push:
    branches-ignore:
      - master
      - MOODLE_[0-9]+_STABLE
    tags-ignore:
      - v[0-9]+.[0-9]+.[0-9]+*

env:
  php: 8.0

jobs:
  Grunt:
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash -l {0}  

    steps:
      - name: Checking out code
        uses: actions/checkout@v2

      - name: Configuring node & npm
        run: nvm install

      - name: Installing node stuff
        run: npm install --loglevel verbose

