name: Core

on:
  push:
    branches-ignore:
      - master
      - MOODLE_[0-9]+_STABLE
    tags-ignore:
      - v[0-9]+.[0-9]+.[0-9]+*

env:
  php: 8.0

jobs:
  Grunt:
    runs-on: ubuntu-18.04

    steps:
      - name: Checking out code
        uses: actions/checkout@v2

      - name: Configuring node & npm
        uses: actions/setup-node@v2
        with: 
          node-version: '14'

      - name: Installing node stuff
        run: npm install

      - name: Running grunt
        run: npx grunt

      - name: Looking for uncommitted changes
        # Add all files to the git index and then run diff --cached to see all changes.
        # This ensures that we get the status of all files, including new files.
        # We ignore npm-shrinkwrap.json to make the tasks immune to npm changes.
        run: |
          git add .
          git reset -- npm-shrinkwrap.json
          git diff --cached --exit-code

